# Generated by Django 5.1.7 on 2025-04-19 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_roll_userattributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('collaboration', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('project', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Urgent', 'Urgent')], default='Personal', max_length=100)),
                ('priority', models.IntegerField(default=1)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
